mohaeng/src/main/java/com/mohaeng/domain/club/domain/Club.java
mohaeng/src/main/java/com/mohaeng/domain/club/domain/ClubMember.java
mohaeng/src/main/java/com/mohaeng/domain/club/domain/ClubRole.java
mohaeng/src/main/java/com/mohaeng/domain/club/domain/enums/ClubRoleCategory.java
mohaeng/src/main/java/com/mohaeng/infrastructure/persistence/database/entity/club/ClubJpaEntity.java
mohaeng/src/main/java/com/mohaeng/infrastructure/persistence/database/entity/club/ClubRoleJpaEntity.java
mohaeng/src/main/java/com/mohaeng/infrastructure/persistence/database/service/club/mapper/ClubPersistenceMapper.java
mohaeng/src/test/java/com/mohaeng/application/club/service/CreateClubTest.java
mohaeng/src/test/java/com/mohaeng/domain/club/domain/ClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/infrastructure/persistence/database/service/member/MemberJpaCommandTest.java
mohaeng/src/test/java/com/mohaeng/infrastructure/persistence/database/service/member/MemberJpaQueryTest.java

feat: 모임 역할 기본 도메인 구현

---

mohaeng/src/docs/asciidoc/alarm/index.adoc
mohaeng/src/docs/asciidoc/authentication/index.adoc
mohaeng/src/docs/asciidoc/club/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/docs/asciidoc/member/index.adoc
mohaeng/src/docs/asciidoc/request-application/index.adoc
mohaeng/src/main/java/com/mohaeng/alarm/application/eventhandler/AlarmEventHandler.java
mohaeng/src/main/java/com/mohaeng/alarm/application/mapper/AlarmApplicationMapper.java
mohaeng/src/main/java/com/mohaeng/alarm/application/service/QueryAlarmById.java
mohaeng/src/main/java/com/mohaeng/alarm/application/usecase/QueryAlarmByIdUseCase.java
mohaeng/src/main/java/com/mohaeng/alarm/application/usecase/dto/AlarmDto.java
mohaeng/src/main/java/com/mohaeng/alarm/domain/model/AlarmMessageGenerateFactory.java
mohaeng/src/main/java/com/mohaeng/alarm/domain/model/AlarmMessageGenerator.java
mohaeng/src/main/java/com/mohaeng/alarm/domain/model/generator/RequestClubJoinAlarmContentGenerator.java
mohaeng/src/main/java/com/mohaeng/alarm/domain/repository/AlarmRepository.java
mohaeng/src/main/java/com/mohaeng/alarm/exception/AlarmException.java
mohaeng/src/main/java/com/mohaeng/alarm/exception/AlarmExceptionType.java
mohaeng/src/main/java/com/mohaeng/alarm/infrastructure/persistence/repository/JpaAlarmRepository.java
mohaeng/src/main/java/com/mohaeng/alarm/presentation/QueryAlarmByIdController.java
mohaeng/src/main/java/com/mohaeng/alarm/presentation/mapper/AlarmControllerMapper.java
mohaeng/src/test/java/com/mohaeng/alarm/application/eventhandler/AlarmEventHandlerTest.java
mohaeng/src/test/java/com/mohaeng/alarm/application/service/QueryAlarmByIdTest.java
mohaeng/src/test/java/com/mohaeng/alarm/domain/model/RequestClubJoinAlarmContentGeneratorTest.java
mohaeng/src/test/java/com/mohaeng/alarm/presentation/QueryAlarmByIdControllerTest.java
mohaeng/src/test/java/com/mohaeng/common/alarm/MockAlarmMessageGenerator.java
mohaeng/src/test/java/com/mohaeng/common/fixtures/AlarmFixture.java
mohaeng/src/test/java/com/mohaeng/common/repositories/MockAlarmRepository.java

feat: 알림 조회 & 읽음 기능을 구현한다.

---

mohaeng/src/main/java/com/mohaeng/common/config/WebConfig.java
mohaeng/src/main/resources/application.yml

fix: 잘못된 URL 요청 시 NOT FOUND 반환하도록 수정

---

mohaeng/src/main/java/com/mohaeng/notification/application/eventhandler/NotificationMakeStrategies.java
mohaeng/src/main/java/com/mohaeng/notification/application/eventhandler/NotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/application/eventhandler/strategy/ApplicationProcessedNotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/application/eventhandler/strategy/ClubJoinApplicationCreatedNotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/application/eventhandler/strategy/OfficerApproveClubJoinApplicationNotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/application/eventhandler/strategy/OfficerRejectClubJoinApplicationNotificationMakeStrategy.java
mohaeng/src/test/java/com/mohaeng/notification/application/eventhandler/NotificationMakeStrategiesTest.java
mohaeng/src/test/java/com/mohaeng/notification/application/eventhandler/strategy/ApplicationProcessedNotificationMakeStrategyTest.java
mohaeng/src/test/java/com/mohaeng/notification/application/eventhandler/strategy/ClubJoinApplicationCreatedNotificationMakeStrategyTest.java
mohaeng/src/test/java/com/mohaeng/notification/application/eventhandler/strategy/OfficerApproveClubJoinApplicationNotificationMakeStrategyTest.java
mohaeng/src/test/java/com/mohaeng/notification/application/eventhandler/strategy/OfficerRejectClubJoinApplicationNotificationMakeStrategyTest.java
mohaeng/src/test/java/com/study/SuperTypeTokenTest.java

refactor: 이벤트 -> 알림 변환 시 성능 개선 & 간편화

---

mohaeng/src/docs/asciidoc/application-form/approve-application/index.adoc
mohaeng/src/docs/asciidoc/application-form/reject-application/index.adoc
mohaeng/src/docs/asciidoc/application-form/request-application/index.adoc
mohaeng/src/docs/asciidoc/authentication/index.adoc
mohaeng/src/docs/asciidoc/club/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/docs/asciidoc/member/index.adoc
mohaeng/src/docs/asciidoc/notification/index.adoc
mohaeng/src/docs/asciidoc/participant/leave/index.adoc
mohaeng/src/main/java/com/mohaeng/applicationform/domain/event/ApplicationProcessedEvent.java
mohaeng/src/main/java/com/mohaeng/applicationform/domain/event/ApplicationProcessedEventHistory.java
mohaeng/src/main/java/com/mohaeng/applicationform/domain/event/ClubJoinApplicationCreatedEventHistory.java
mohaeng/src/main/java/com/mohaeng/applicationform/domain/event/OfficerApproveClubJoinApplicationEvent.java
mohaeng/src/main/java/com/mohaeng/applicationform/domain/event/OfficerApproveClubJoinApplicationEventHistory.java
mohaeng/src/main/java/com/mohaeng/applicationform/domain/event/OfficerRejectClubJoinApplicationEvent.java
mohaeng/src/main/java/com/mohaeng/applicationform/domain/event/OfficerRejectClubJoinApplicationEventHistory.java
mohaeng/src/main/java/com/mohaeng/club/domain/event/CreateClubEventHistory.java
mohaeng/src/main/java/com/mohaeng/clubrole/domain/event/CreateDefaultRoleHistory.java
mohaeng/src/main/java/com/mohaeng/common/notification/NotificationEvent.java
mohaeng/src/main/java/com/mohaeng/notification/application/dto/NotificationDto.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/kind/ApplicationProcessedNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/kind/ClubJoinApplicationCreatedNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/kind/ExpelParticipantNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/kind/OfficerApproveApplicationNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/kind/OfficerRejectApplicationNotification.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/response/NotificationResponse.java
mohaeng/src/main/java/com/mohaeng/participant/domain/event/ExpelParticipantEvent.java
mohaeng/src/main/java/com/mohaeng/participant/domain/event/ExpelParticipantEventHistory.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/QueryNotificationByIdControllerTest.java

refactor: final관련 수정, DiscriminatorValue 수정, 테스트코드 수정

---

mohaeng/src/main/java/com/mohaeng/common/event/Events.java
mohaeng/src/test/java/com/mohaeng/applicationform/application/service/ApproveJoinClubTest.java
mohaeng/src/test/java/com/mohaeng/applicationform/application/service/RejectJoinClubTest.java
mohaeng/src/test/java/com/mohaeng/applicationform/application/service/RequestJoinClubTest.java
mohaeng/src/test/java/com/mohaeng/club/application/service/CreateClubTest.java
mohaeng/src/test/java/com/mohaeng/clubrole/application/eventhandler/CreateDefaultRoleWithCreateClubEventsHandlerTest.java
mohaeng/src/test/java/com/mohaeng/common/annotation/ApplicationTest.java

refactor: 이벤트 발행 테스트 개선

---

mohaeng/src/docs/asciidoc/clubrole/change-name/index.adoc
mohaeng/src/docs/asciidoc/clubrole/create/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/clubrole/application/usecase/ChangeClubRoleNameUseCase.java
mohaeng/src/main/java/com/mohaeng/clubrole/domain/model/ClubRole.java
mohaeng/src/main/java/com/mohaeng/clubrole/domain/repository/ClubRoleRepository.java
mohaeng/src/main/java/com/mohaeng/clubrole/exception/ClubRoleExceptionType.java
mohaeng/src/main/java/com/mohaeng/clubrole/infrastructure/persistence/database/repository/JpaClubRoleRepository.java
mohaeng/src/main/java/com/mohaeng/clubrole/presentation/ChangeClubRoleNameController.java
mohaeng/src/main/java/com/mohaeng/participant/application/service/ChangeClubRoleName.java
mohaeng/src/main/java/com/mohaeng/participant/domain/model/Participant.java
mohaeng/src/test/java/com/mohaeng/clubrole/presentation/ChangeClubRoleNameControllerTest.java
mohaeng/src/test/java/com/mohaeng/common/repositories/MockClubRoleRepository.java
mohaeng/src/test/java/com/mohaeng/participant/application/service/ChangeClubRoleNameTest.java

feat: 역할 이름 변경 기능 구현

---

mohaeng/src/docs/asciidoc/application-form/approve-application/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/applicationform/domain/model/ApplicationForm.java
mohaeng/src/main/java/com/mohaeng/participant/application/service/ExpelParticipant.java
mohaeng/src/main/java/com/mohaeng/participant/domain/model/Participant.java
mohaeng/src/main/java/com/mohaeng/participant/domain/repository/ParticipantRepository.java
mohaeng/src/main/java/com/mohaeng/participant/infrastructure/persistence/database/repository/JpaParticipantRepository.java
mohaeng/src/test/java/com/mohaeng/applicationform/domain/ApplicationFormTest.java
mohaeng/src/test/java/com/mohaeng/applicationform/presentation/ApproveJoinClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/clubrole/domain/model/ClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/common/repositories/MockParticipantRepository.java
mohaeng/src/test/java/com/mohaeng/participant/application/service/ExpelParticipantTest.java
mohaeng/src/test/java/com/mohaeng/participant/domain/model/ParticipantTest.java

test: 작성하지 않은 도메인 로직 테스트 작성

---

mohaeng/src/docs/asciidoc/application-form/approve-application/index.adoc
mohaeng/src/docs/asciidoc/application-form/reject-application/index.adoc
mohaeng/src/docs/asciidoc/application-form/request-application/index.adoc
mohaeng/src/docs/asciidoc/authentication/index.adoc
mohaeng/src/docs/asciidoc/club/create/index.adoc
mohaeng/src/docs/asciidoc/club/delete/index.adoc
mohaeng/src/docs/asciidoc/clubrole/change-name/index.adoc
mohaeng/src/docs/asciidoc/clubrole/create/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/docs/asciidoc/member/index.adoc
mohaeng/src/docs/asciidoc/notification/index.adoc
mohaeng/src/docs/asciidoc/participant/expel/index.adoc
mohaeng/src/docs/asciidoc/participant/leave/index.adoc
mohaeng/src/main/resources/static/docs/application-form/approve-application/index.html
mohaeng/src/main/resources/static/docs/application-form/reject-application/index.html
mohaeng/src/main/resources/static/docs/application-form/request-application/index.html
mohaeng/src/main/resources/static/docs/authentication/index.html
mohaeng/src/main/resources/static/docs/club/create/index.html
mohaeng/src/main/resources/static/docs/club/delete/index.html
mohaeng/src/main/resources/static/docs/clubrole/change-name/index.html
mohaeng/src/main/resources/static/docs/clubrole/create/index.html
mohaeng/src/main/resources/static/docs/index.html
mohaeng/src/main/resources/static/docs/member/index.html
mohaeng/src/main/resources/static/docs/notification/index.html
mohaeng/src/main/resources/static/docs/participant/expel/index.html
mohaeng/src/main/resources/static/docs/participant/leave/index.html

docs: API 문서 수정

---

mohaeng/src/docs/asciidoc/clubrole/change-default-role/index.adoc
mohaeng/src/docs/asciidoc/clubrole/change-name/index.adoc
mohaeng/src/docs/asciidoc/clubrole/delete/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/clubrole/application/usecase/ChangeDefaultRoleUseCase.java
mohaeng/src/main/java/com/mohaeng/clubrole/domain/model/ClubRole.java
mohaeng/src/main/java/com/mohaeng/clubrole/exception/ClubRoleExceptionType.java
mohaeng/src/main/java/com/mohaeng/clubrole/presentation/ChangeClubRoleNameController.java
mohaeng/src/main/java/com/mohaeng/clubrole/presentation/ChangeDefaultRoleController.java
mohaeng/src/main/java/com/mohaeng/participant/application/service/ChangeDefaultRole.java
mohaeng/src/main/java/com/mohaeng/participant/domain/model/Participant.java
mohaeng/src/test/java/com/mohaeng/clubrole/domain/model/ClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/clubrole/presentation/ChangeClubRoleNameControllerTest.java
mohaeng/src/test/java/com/mohaeng/clubrole/presentation/ChangeDefaultRoleControllerTest.java
mohaeng/src/test/java/com/mohaeng/clubrole/presentation/DeleteClubRoleControllerTest.java
mohaeng/src/test/java/com/mohaeng/participant/application/service/ChangeDefaultRoleTest.java
mohaeng/src/test/java/com/mohaeng/participant/domain/model/ParticipantTest.java

feat: 모임의 기본 역할 변경 기능 구현

---

mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/docs/asciidoc/participant/change-role/index.adoc
mohaeng/src/main/java/com/mohaeng/clubrole/application/usecase/ChangeTargetClubRoleUseCase.java
mohaeng/src/main/java/com/mohaeng/clubrole/domain/model/ClubRole.java
mohaeng/src/main/java/com/mohaeng/clubrole/domain/model/ClubRoleCategory.java
mohaeng/src/main/java/com/mohaeng/clubrole/exception/ClubRoleExceptionType.java
mohaeng/src/main/java/com/mohaeng/participant/application/service/ChangeTargetClubRole.java
mohaeng/src/main/java/com/mohaeng/participant/application/usecase/ChangeTargetClubRoleUseCase.java
mohaeng/src/main/java/com/mohaeng/participant/domain/model/Participant.java
mohaeng/src/main/java/com/mohaeng/participant/domain/repository/ParticipantRepository.java
mohaeng/src/main/java/com/mohaeng/participant/exception/ParticipantExceptionType.java
mohaeng/src/main/java/com/mohaeng/participant/infrastructure/persistence/database/repository/JpaParticipantRepository.java
mohaeng/src/main/java/com/mohaeng/participant/presentation/ChangeTargetClubRoleController.java
mohaeng/src/test/java/com/mohaeng/applicationform/domain/ApplicationFormTest.java
mohaeng/src/test/java/com/mohaeng/clubrole/domain/model/ClubRoleCategoryTest.java
mohaeng/src/test/java/com/mohaeng/clubrole/domain/model/ClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/common/repositories/MockParticipantRepository.java
mohaeng/src/test/java/com/mohaeng/participant/application/service/ChangeTargetClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/participant/domain/model/ParticipantTest.java
mohaeng/src/test/java/com/mohaeng/participant/presentation/ChangeTargetClubRoleControllerTest.java

feat: 참여자 역할 변경 기능 구현

---

mohaeng/src/main/java/com/mohaeng/notification/application/dto/NotificationDto.java
mohaeng/src/main/java/com/mohaeng/notification/application/eventhandler/NotificationEventHandler.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/Notification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/NotificationMakeStrategies.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/NotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/Receiver.java
mohaeng/src/main/java/com/mohaeng/notification/domain/repository/NotificationRepository.java
mohaeng/src/main/java/com/mohaeng/notification/infrastructure/persistence/repository/JpaNotificationRepository.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/response/NotificationResponse.java
mohaeng/src/test/java/com/mohaeng/notification/application/eventhandler/NotificationEventHandlerTest.java
mohaeng/src/test/java/com/mohaeng/notification/domain/model/NotificationMakeStrategiesTest.java
mohaeng/src/test/java/com/mohaeng/notification/domain/model/NotificationMakeStrategyTest.java
mohaeng/src/test/java/com/mohaeng/notification/domain/model/NotificationTest.java
mohaeng/src/test/java/com/mohaeng/notification/mock/MockEventHistory.java
mohaeng/src/test/java/com/mohaeng/notification/mock/MockNotification.java
mohaeng/src/test/java/com/mohaeng/notification/mock/MockNotificationConfig.java
mohaeng/src/test/java/com/mohaeng/notification/mock/MockNotificationEvent.java
mohaeng/src/test/java/com/mohaeng/notification/mock/MockNotificationMakeStrategy.java

feat: 알림 기능 구현

---

mohaeng/src/docs/asciidoc/club/participant/expel/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/ExpelParticipant.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/ExpelParticipantUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/event/ExpelParticipantEvent.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/event/history/ExpelParticipantEventHistory.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Club.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Participant.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Participants.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ParticipantExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/ExpelParticipantController.java
mohaeng/src/main/java/com/mohaeng/notification/application/dto/type/ExpelParticipantNotificationDto.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/strategy/ExpelParticipantNotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/ExpelParticipantNotification.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/response/type/ExpelParticipantNotificationResponse.java
mohaeng/src/test/java/com/mohaeng/club/applicationform/domain/ApplicationFormTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/CreateClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ExpelParticipantTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ParticipantTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ParticipantsTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/ExpelParticipantControllerTest.java
mohaeng/src/test/java/com/mohaeng/common/fixtures/ApplicationFormFixture.java
mohaeng/src/test/java/com/mohaeng/common/fixtures/ClubFixture.java
mohaeng/src/test/java/com/mohaeng/common/fixtures/MemberFixture.java
mohaeng/src/test/java/com/mohaeng/member/application/service/SignUpTest.java
mohaeng/src/test/java/com/mohaeng/member/domain/model/MemberTest.java

refactor: 모임에서 추방하는 기능 구현

---

mohaeng/src/main/java/com/mohaeng/club/applicationform/application/eventhandler/DeleteApplicationFormWithDeleteClubEventHandler.java
mohaeng/src/main/java/com/mohaeng/club/applicationform/domain/event/DeleteApplicationFormEvent.java
mohaeng/src/main/java/com/mohaeng/club/applicationform/domain/event/history/DeleteApplicationFormEventHistory.java
mohaeng/src/main/java/com/mohaeng/club/applicationform/domain/repository/ApplicationFormRepository.java
mohaeng/src/main/java/com/mohaeng/club/applicationform/infrastructure/persistence/database/repository/JpaApplicationFormRepository.java
mohaeng/src/main/java/com/mohaeng/club/club/application/service/DeleteClub.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/DeleteClubUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/event/DeleteClubEvent.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/event/history/DeleteClubEventHistory.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Club.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/repository/ClubRepository.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ClubExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/DeleteClubController.java
mohaeng/src/main/java/com/mohaeng/notification/application/dto/type/DeleteApplicationFormCauseByClubDeletedNotificationDto.java
mohaeng/src/main/java/com/mohaeng/notification/application/dto/type/DeleteParticipantCauseByClubDeletedNotificationDto.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/strategy/DeleteApplicationFormCauseByClubDeletedNotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/strategy/DeleteParticipantCauseByClubDeletedNotificationMakeStrategy.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/DeleteApplicationFormCauseByClubDeletedNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/DeleteParticipantCauseByClubDeletedNotification.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/response/type/DeleteApplicationFormCauseByClubDeletedNotificationResponse.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/response/type/DeleteParticipantCauseByClubDeletedNotificationResponse.java
mohaeng/src/test/java/com/mohaeng/club/applicationform/application/eventhandler/DeleteApplicationFormWithDeletedClubEventHandlerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/DeleteClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/DeleteClubControllerTest.java

refactor: 모임 제거 기능 구현

---

mohaeng/src/docs/asciidoc/club/clubrole/create/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/CreateClubRole.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/CreateClubRoleUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Club.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/ClubRoles.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ClubRoleExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/CreateRoleController.java
mohaeng/src/test/java/com/mohaeng/club/applicationform/presentation/FillOutApplicationFormControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ChangeParticipantRoleTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/CreateClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/CreateClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/DeleteClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ExpelParticipantTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/LeaveClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubRolesTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/CreateClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/CreateRoleControllerTest.java

refactor: 모임 역할 생성 기능 재구현

---

mohaeng/src/docs/asciidoc/club/clubrole/change-name/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/ChangeClubRoleName.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/ChangeClubRoleNameUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Club.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/ClubRole.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/ClubRoles.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ClubRoleExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/ChangeClubRoleNameController.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ChangeClubRoleNameTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubRolesTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/ChangeClubRoleNameControllerTest.java

refactor: 역할 이름 변경 기능 구현

---

mohaeng/src/docs/asciidoc/club/clubrole/delete/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/DeleteClubRole.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/DeleteClubRoleUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Club.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/ClubRoles.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Participants.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ClubRoleExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/DeleteClubRoleController.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/DeleteClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubRolesTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/DeleteClubRoleControllerTest.java
mohaeng/src/test/java/com/study/NestedTestInitTest.java

refactor: 역할 제거 기능 구현

---

mohaeng/src/docs/asciidoc/club/clubrole/change-default-role/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/ChangeDefaultRole.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/ChangeDefaultRoleUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Club.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/ClubRole.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/ClubRoles.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ClubRoleExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/ChangeDefaultRoleController.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ChangeClubRoleNameTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ChangeDefaultRoleTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ChangeParticipantRoleTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/CreateClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/DeleteClubRoleTest.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/ExpelParticipantTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubRolesTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/ChangeDefaultRoleControllerTest.java

refactor: 모임의 기본 역할을 변경하는 기능 구현

---

mohaeng/src/docs/asciidoc/club/clubrole/create/index.adoc
mohaeng/src/docs/asciidoc/club/participant/delete-president/index.adoc
mohaeng/src/docs/asciidoc/index.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/DelegatePresident.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/DelegatePresidentUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Club.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/model/Participants.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ParticipantExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/CreateClubController.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/DelegatePresidentController.java
mohaeng/src/main/java/com/mohaeng/member/presentation/SignUpController.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/DelegatePresidentTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/domain/model/ParticipantsTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/CreateClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/CreateRoleControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/DelegatePresidentControllerTest.java

feat: 회장 위임 기능 구현

---

mohaeng/src/main/java/com/mohaeng/authentication/presentation/config/AuthenticationConfig.java
mohaeng/src/main/java/com/mohaeng/common/interceptor/PathAndMethodMapping.java
mohaeng/src/main/java/com/mohaeng/common/interceptor/PathAndMethodMatcherInterceptor.java
mohaeng/src/test/java/com/mohaeng/common/interceptor/PathAndMethodMappingTest.java

feat: 인터셉터 등록 시 HttpMethod도 함께 등록할 수 있도록 구현

---

mohaeng/src/test/java/com/mohaeng/authentication/presentation/LogInControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/applicationform/presentation/ApproveApplicationFormControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/applicationform/presentation/FillOutApplicationFormControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/applicationform/presentation/RejectApplicationFormControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/ChangeClubRoleNameControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/ChangeDefaultRoleControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/ChangeParticipantRoleControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/CreateClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/CreateRoleControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/DelegatePresidentControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/DeleteClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/DeleteClubRoleControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/ExpelParticipantControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/command/LeaveClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/QueryClubByIdControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/SearchClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/common/presentation/RequestBuilder.java
mohaeng/src/test/java/com/mohaeng/member/presentation/SignUpControllerTest.java

refactor: RequestBuilder 과정 간편화

---

README.md
mohaeng/src/docs/asciidoc/club/club.adoc
mohaeng/src/docs/asciidoc/notification/index.adoc
mohaeng/src/main/java/com/mohaeng/notification/application/service/query/QueryAllNotification.java
mohaeng/src/main/java/com/mohaeng/notification/application/service/query/QueryNotificationById.java
mohaeng/src/main/java/com/mohaeng/notification/application/usecase/query/QueryAllNotificationUseCase.java
mohaeng/src/main/java/com/mohaeng/notification/application/usecase/query/QueryNotificationByIdUseCase.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/Notification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/ApplicationProcessedNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/DeleteParticipantCauseByClubDeletedNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/ExpelParticipantNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/FillOutApplicationFormNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/OfficerApproveApplicationNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/OfficerRejectApplicationNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/ParticipantClubRoleChangedNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/repository/NotificationQueryRepository.java
mohaeng/src/main/java/com/mohaeng/notification/domain/repository/NotificationRepository.java
mohaeng/src/main/java/com/mohaeng/notification/exception/NotificationException.java
mohaeng/src/main/java/com/mohaeng/notification/exception/NotificationExceptionType.java
mohaeng/src/main/java/com/mohaeng/notification/infrastructure/persistence/repository/JpaNotificationQueryRepository.java
mohaeng/src/main/java/com/mohaeng/notification/infrastructure/persistence/repository/JpaNotificationRepository.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/QueryAllNotificationController.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/QueryNotificationByIdController.java
mohaeng/src/test/java/com/mohaeng/common/fixtures/NotificationFixture.java
mohaeng/src/test/java/com/mohaeng/common/presentation/RequestBuilder.java
mohaeng/src/test/java/com/mohaeng/common/util/RepositoryUtil.java
mohaeng/src/test/java/com/mohaeng/notification/application/service/query/QueryAllNotificationTest.java
mohaeng/src/test/java/com/mohaeng/notification/application/service/query/QueryNotificationByIdTest.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/QueryAllNotificationControllerTest.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/QueryNotificationByIdControllerTest.java

feat: 알림 조회 기능 구현

---

mohaeng/src/docs/asciidoc/notification/index.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/query/QueryAllClubBySearchCond.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/query/QueryAllClubBySearchCondUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/infrastructure/persistence/database/repository/JpaClubQueryRepository.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/query/SearchClubController.java
mohaeng/src/main/java/com/mohaeng/notification/application/dto/type/FillOutApplicationFormNotificationDto.java
mohaeng/src/main/java/com/mohaeng/notification/application/service/query/QueryAllNotification.java
mohaeng/src/main/java/com/mohaeng/notification/application/service/query/QueryFillOutApplicationFormNotification.java
mohaeng/src/main/java/com/mohaeng/notification/application/usecase/query/QueryAllNotificationUseCase.java
mohaeng/src/main/java/com/mohaeng/notification/application/usecase/query/QueryFillOutApplicationFormNotificationUseCase.java
mohaeng/src/main/java/com/mohaeng/notification/domain/model/type/FillOutApplicationFormNotification.java
mohaeng/src/main/java/com/mohaeng/notification/domain/repository/NotificationQueryRepository.java
mohaeng/src/main/java/com/mohaeng/notification/infrastructure/persistence/repository/JpaNotificationQueryRepository.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/QueryAllNotificationController.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/QueryFillOutApplicationFormNotificationController.java
mohaeng/src/main/java/com/mohaeng/notification/presentation/response/NotificationResponse.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/query/QueryAllClubBySearchCondTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/SearchClubControllerTest.java
mohaeng/src/test/java/com/mohaeng/common/fixtures/NotificationFixture.java
mohaeng/src/test/java/com/mohaeng/notification/application/service/query/QueryAllNotificationTest.java
mohaeng/src/test/java/com/mohaeng/notification/application/service/query/QueryFillOutApplicationFormNotificationTest.java
mohaeng/src/test/java/com/mohaeng/notification/application/service/query/QueryNotificationByIdTest.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/QueryAllNotificationControllerTest.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/QueryFillOutApplicationFormNotificationControllerTest.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/QueryNotificationByIdControllerTest.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/response/NotificationResponseTestImpl.java

feat: 가입 신청 요청 알림에 대한 조회 기능을 구현한다.

---

mohaeng/build.gradle
mohaeng/src/docs/asciidoc/club/participant.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/query/ExportParticipantsToExcel.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/query/ExportParticipantsToExcelUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ParticipantExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/query/ExportParticipantToExcelController.java
mohaeng/src/main/java/com/mohaeng/common/util/ExcelExporter.java
mohaeng/src/test/java/com/mohaeng/club/club/infrastructure/export/excel/ExportParticipantsToExcelTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/ExportParticipantToExcelControllerTest.java
mohaeng/src/test/java/com/mohaeng/notification/presentation/QueryAllNotificationControllerTest.java

feat: 모임 참여자 명단을 엑셀로 내보내는 기능 구현

---

mohaeng/src/docs/asciidoc/club/participant.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/query/QueryParticipantsByClubId.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/query/QueryParticipantsByClubIdUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/repository/ParticipantQueryRepository.java
mohaeng/src/main/java/com/mohaeng/club/club/exception/ParticipantExceptionType.java
mohaeng/src/main/java/com/mohaeng/club/club/infrastructure/persistence/database/repository/JpaParticipantQueryRepository.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/query/QueryParticipantsByClubIdController.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/query/QueryParticipantsByClubIdTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/ExportParticipantToExcelControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/QueryParticipantsByClubIdControllerTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/SearchClubControllerTest.java

feat: 모임에 가입한 참여자 전체 조회 기능 구현

---

mohaeng/src/docs/asciidoc/club/club.adoc
mohaeng/src/main/java/com/mohaeng/club/club/application/service/query/QueryParticipatedClub.java
mohaeng/src/main/java/com/mohaeng/club/club/application/usecase/query/QueryParticipatedClubUseCase.java
mohaeng/src/main/java/com/mohaeng/club/club/domain/repository/ClubQueryRepository.java
mohaeng/src/main/java/com/mohaeng/club/club/infrastructure/persistence/database/repository/JpaClubQueryRepository.java
mohaeng/src/main/java/com/mohaeng/club/club/presentation/query/QueryParticipatedClubController.java
mohaeng/src/test/java/com/mohaeng/club/club/application/service/query/QueryParticipatedClubTest.java
mohaeng/src/test/java/com/mohaeng/club/club/presentation/query/QueryParticipatedClubControllerTest.java

feat: 내가 참여한 모임 조회하는 기능 구현
